---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-server
  namespace: devops
  labels:
    app: hello-server
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: hello-server
  template:
    metadata:
      labels:
        app: hello-server
    spec:
      containers:
        - name: hello-server
          image: image-registry.openshift-image-registry.svc:5000/devops/hello-server:v1
          resources:
            request:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 8000
              protocol: TCP